# docker-compose.yml: Manages the PostgreSQL service.
---
version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: jekwwer_pgsql_workspace
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: mydatabase
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
